name: Waka Readme

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]
   schedule:
    # Runs at 12am IST
   - cron: "0 12 * * "
   workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Profile Readme Development Stats
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
